//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 05:58:11 PM CET 
//


package eu.fbk.das.adaptation.ensemble;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Abstract activity to be refined by Adaptation Manager
 * 				using its goal
 * 			
 * 
 * <p>Java class for abstractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstractType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://das.fbk.eu/Process}activityType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="receiveGoal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="goal" type="{http://das.fbk.eu/Annotation}GoalType"/>
 *         &lt;/choice>
 *         &lt;element name="compensation" type="{http://das.fbk.eu/Annotation}CompensationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractType", propOrder = {
    "receiveGoal",
    "goal",
    "compensation"
})
public class AbstractType
    extends ActivityType
{

    protected String receiveGoal;
    protected GoalType goal;
    protected CompensationType compensation;

    /**
     * Gets the value of the receiveGoal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiveGoal() {
        return receiveGoal;
    }

    /**
     * Sets the value of the receiveGoal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiveGoal(String value) {
        this.receiveGoal = value;
    }

    /**
     * Gets the value of the goal property.
     * 
     * @return
     *     possible object is
     *     {@link GoalType }
     *     
     */
    public GoalType getGoal() {
        return goal;
    }

    /**
     * Sets the value of the goal property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoalType }
     *     
     */
    public void setGoal(GoalType value) {
        this.goal = value;
    }

    /**
     * Gets the value of the compensation property.
     * 
     * @return
     *     possible object is
     *     {@link CompensationType }
     *     
     */
    public CompensationType getCompensation() {
        return compensation;
    }

    /**
     * Sets the value of the compensation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensationType }
     *     
     */
    public void setCompensation(CompensationType value) {
        this.compensation = value;
    }

}
