//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 05:58:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://das.fbk.eu/Process", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.fbk.das.adaptation.ensemble;
