//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 05:58:11 PM CET 
//


package eu.fbk.das.adaptation.ensemble;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * An activity to be performed when a message with given
 * 				name is received
 * 			
 * 
 * <p>Java class for receiveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="receiveType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://das.fbk.eu/Process}activityType">
 *       &lt;sequence>
 *         &lt;element name="compensation" type="{http://das.fbk.eu/Annotation}CompensationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "receiveType", propOrder = {
    "compensation"
})
public class ReceiveType
    extends ActivityType
{

    protected CompensationType compensation;

    /**
     * Gets the value of the compensation property.
     * 
     * @return
     *     possible object is
     *     {@link CompensationType }
     *     
     */
    public CompensationType getCompensation() {
        return compensation;
    }

    /**
     * Sets the value of the compensation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensationType }
     *     
     */
    public void setCompensation(CompensationType value) {
        this.compensation = value;
    }

}
